foodmenu/food/urls.py
from django.urls import path
from . import views

app_name = 'food'

urlpatterns = [
    path('item/', views.ItemClassView.as_view() , name= 'item'),
    path('<int:pk>/', views.ItemDetails.as_view(), name = "details"),
    path('add_items/', views.AddItemView.as_view(), name="add_items"),
    path('update_items/<int:item_id>/', views.update_items, name="update_items"),
    path('delete_item/<int:id>/', views.delete_items, name='delete_item'),  # Ensure the name is 'delete_item'
]

foodmenu/foodmenu/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name ='users/login.html'), name="login"),
    path('logout/', user_views.logout_view, name="logout"),
    path('profile/', user_views.profile_page, name="profile"),
]

urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

foodmenu/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.


class Item(models.Model):
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=8)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(
        max_length=500, 
        default="https://images.jdmagicbox.com/comp/darjeeling/h1/9999px354.x354.181016125224.y3h1/catalogue/random-fast-food-pedong-darjeeling-fast-food-b66reu0l8c-250.jpg")

    def get_absolute_url(self):
        return reverse("food:details", kwargs={"pk": self.pk})
    

foodmenu/users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default="profilepic.png", upload_to="profile_pictures")
    location = models.CharField(max_length=100)
    def __str__(self):
        return self.user.username
# Create your models here.

foodmenu/food/forms.py
from django import forms 
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

foodmenu/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=100)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

    

foodmenu/food/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView 
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
# def items(request):
#     item_list = Item.objects.all()
#     template = loader.get_template('food/items.html')
#     context = {
#         'item_list':item_list,
#     }
#     return render(request, "food/items.html", context=context)

def details(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        "item":item,
    }
    return render(request, 'food/details.html', context=context)

def add_items(request):
    form = ItemForm(request.POST or None)

    if form.is_valid():
        form.save()
        return redirect('food:item')
    return render(request, 'food/item_form.html', {'form':form})

class AddItemView(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']

    def form_valid(self, form):
        form.instance.username = self.request.user

        return super().form_valid(form)
    
    template_name = 'food/item_form.html'


def update_items(request, item_id):
    item = Item.objects.get(id = item_id)

    form = ItemForm(request.POST or None, instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:item')
    return render(request, 'food/item_form.html', {'form':form})

def delete_items(request, id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:item')
    return render(request, 'food/item_delete.html', {'item':item})

class ItemClassView(ListView):
    model = Item
    template_name = 'food/items.html'
    context_object_name = 'item_list'

class ItemDetails(DetailView):
    model = Item
    template_name = 'food/details.html'

foodmenu/users/views.py
from django.shortcuts import redirect, render
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView

# Create your views here.
def register(request):
    if(request.method == 'POST'):
        form = RegisterForm(request.POST)   
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"welcome {username}.")
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form':form})

def logout_view(request):
    logout(request)
    return redirect('food:item')

@login_required
def profile_page(request):
    return render(request, "users/profile.html")

foodmenu/food/templates/food/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <a href="#" class= "navbar-brand">Food</a>
        <div class="nav">
            <a class="nav-item nav-link" href="#">Add item</a>
            <a class="nav-item nav-link" href="#">Delete item</a>
            <a class="nav-item nav-link" href="#">View item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}">Logout</a>
                <a href="{%url 'profile' %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{%url 'profile' %}">Profile</a>
            {% endif %}
            </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
            <div clsaa="alert alert-{{message.tag}}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {%block body%}
    {%endblock%}
    
</body>
</html>

foodmenu/food/templates/food/details.html
{% extends "food/base.html"%}
{% block body%}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img style="height:300px" src="{{ item.item_image }}" alt="item.item_image" class="card">
        </div>
        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>{{object.item_desc}}</h2>
            <h2>${{object.item_price}}</h2>
            <a href="{% url 'food:delete_item' item.id %}" class="">Delete</a>
        </div>
    </div>
    
</div>

{% endblock %}

foodmenu/food/templates/food/item_delete.html
{% extends 'food/base.html' %}
{%block body%}
<form method="POST"> 
    {%csrf_token%}
    <h1>Sure wanna delete {{item.item_name}}</h1>
    <button type="submit">Confirm</button>
</form>
{%endblock%}

foodmenu/food/templates/food/item_form.html
{%extends "food/base.html"%}
{% block body %}
<div class="container">
    <div class="row">
        <dev class="col-md-4 offset-md-4">
            <div class="card">
                <div class="card-header  text-white bg-info ">
                    <div class="card-title ">Login</div>
                </div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {%for field in form%}
                          <div class="form-group">
                            {{field.name}}
                            {{field}}                               
                        </div>
                        {%endfor%}
                        <button  type="submit" class="btn-info" >Save</button> 
                    </form>
                </div>
            </div>
        </dev>
    </div>
</div>
{% endblock %}

foodmenu/food/templates/food/items.html
{% extends "food/base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {%block body%}
        {% for item in item_list%}
            <div class="row">
                <div class="col-md-3 offset-md-2">
                    <img src="{{item.item_image}}" alt="imagecomingsoon" class="card" style="height:150px">
                </div> 
                <div class="col-md-4">
                    <h3>{{item.item_name}}</h3>
                    <h5>{{item.item_desc}}</h5>
                    <h5>${{item.item_price}}</h5>
                    <h6>{{item.user_name}}</h6>
                </div>
                <div class="col-md-2">
                    <a href="{% url 'food:details' item.id %}" class="btn btn-success">Details</a>
                </div>
            </div>
        {% comment %} <ul>
            <li>
                <a href="{% url 'food:details' item.id %}">{{ item.id }} --- {{ item.item_name }}</a>
            </li>
        </ul> {% endcomment %}
        {% endfor%}
    {% endblock%}
</body>
</html>

foodmenu/users/templates/users/login.html
<form method="POST">
    {% csrf_token %} 
    {{form}}
    <button type="submit">Login</button>   
<form>

foodmenu/users/templates/users/logout.html
<form method="POST" action="{% url 'logout' %}">
    {% csrf_token %}
    {{form}}
    <button type="submit">Logout</button>
</form>

foodmenu/users/templates/users/profile.html
{% load static %}
<h1>{{ user.username }}</h1>
<img src="{% static "food_menu_app/foodmenu/pictures/profilepic.png" %}" style="height:300px">

foodmenu/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">submit</form>
</form>